// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.dealermenu.domain;

import net.dealermenu.domain.Fee;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Fee_Roo_Configurable {
    
    declare @type: Fee: @Configurable;
    
}
